### ISSUE TITLE
Port to OMP

### ISSUE THREAD

**Issue by ajnyga** [ajnyga/disqus#3]
Would probably not need much changes, maybe just a secondary template hook.

**Comment by asmecher** [comment]
+1 on this!

**Comment by ajnyga** [comment]
@asmecher 
Everything else is ready except for this:
“I also did the needed changes for disqus plugin, but OMP does not have the required template hook. Of course I could do a smarty filter, but those are pretty horrible…
See https://github.com/pkp/ojs/blob/master/templates/frontend/pages/article.tpl#L29 and compare to https://github.com/pkp/omp/blob/master/templates/frontend/pages/book.tpl1”

If that hooks looks like a good idea for OMP, I can do a pr

**Comment by asmecher** [comment]
Please do! The more we can standardize hook conventions between OJS and OMP, the better.

**Comment by ajnyga** [comment]
Hi @asmecher  see https://github.com/pkp/omp/pull/514

I did start to wonder what this hook is. Is viewFile.tpl something that replaces the pdf.js plugin in OMP or what?
https://github.com/pkp/omp/blob/master/templates/frontend/pages/viewFile.tpl#L58

**Comment by asmecher** [comment]
@ajnyga, `viewFile.tpl` (and the code that used to call on it, `ViewableFilePlugin.inc.php`) are both dead code -- there was previously a "viewable file" plugin category, but that was replaced by generic plugins to accomplish the same thing. (I've removed both those files.)
