### ISSUE TITLE
how to install in ojs 3.1.1 (php 7)

### ISSUE THREAD

**Issue by cristiaan3003** [ajnyga/disqus#5]
Hi. Can it be installed in 3.1.1 (ojs) with php 7?

Regards
Cristian

**Comment by ajnyga** [comment]
Hi,

I think I have not tested this with 3.1.1 yet, but basically you just download it, unzip, rename the folder to "disqus" and upload to the plugins/generic folder of your OJS.

Then you activate the plugin and register a Disqus account and edit the settings of the plugin. That should be it. But as I said, I do not know if it works with 3.1.1. Let me know.

**Comment by cristiaan3003** [comment]
I installed it according to the indicated steps and it worked. Thank you very much.

Regards
