### ISSUE TITLE
OJS 3.1.2

### ISSUE THREAD

**Issue by eddoff** [ajnyga/disqus#7]
This plugin does not work with the 3.1.2.0 OJS-version. Can you please update?

**Comment by ajnyga** [comment]
Sorry at the moment it does not. I will upgrade it within the next week probably.

**Comment by mpbraendle** [comment]
I have adapted it to run with OJS 3.1.2-1 . See pull request.

**Comment by ajnyga** [comment]
thanks @mpbraendle, I merged your pr. I will probably not upgrade this actively in the future while we have no users of our own for it.
